pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Generate Allure Report') {
            steps {
                allure(
                        includeProperties: false,
                        jdk: '',
                        results: [[path: 'allure-results']]
                )
            }
        }

        stage('Trigger Report Job') {
            steps {
                build job: 'Report_Job'
            }
        }
    }

    post {

        always {
            junit '**/surefire-reports/*.xml'
            archiveArtifacts artifacts: '**/allure-results/*', fingerprint: true
        }

        success {
            echo 'Build Passed'
        }

        failure {
            echo 'Build Failed'
        }
    }
}